// Convenience type aliases over the generated OpenAPI schema.
//
// api.ts is fully regenerated by `npm run generate:types` (the
// openapi-typescript CLI overwrites the whole file, wiping out anything
// hand-added there). This file is never touched by that command, so it's
// the permanent home for named type aliases -- add new ones here, never in
// api.ts, and nothing is ever lost on a regen again.
import type { components } from "./api";

export type PipelineOpportunity = components["schemas"]["PipelineOpportunity"];
export type PipelinePage = components["schemas"]["PaginatedResponse_PipelineOpportunity_"];
export type SplitResponse = components["schemas"]["SplitResponse"];
export type StakeholderLinkResponse = components["schemas"]["StakeholderLinkResponse"];
export type OpportunityItemResponse = components["schemas"]["OpportunityItemResponse"];
export type ReminderResponse = components["schemas"]["ReminderResponse"];
export type ActivityResponse = components["schemas"]["ActivityResponse"];
export type ActivityPage = components["schemas"]["PaginatedResponse_ActivityResponse_"];
export type ActivityType = components["schemas"]["ActivityResponse"]["activity_type"];
export type ActivityReportRow = components["schemas"]["ActivityReportRow"];
export type ActivityReportPage = components["schemas"]["PaginatedResponse_ActivityReportRow_"];
export type OpportunityForStakeholder = components["schemas"]["OpportunityForStakeholder"];
export type StakeholderOpportunityCountsEntry = components["schemas"]["StakeholderOpportunityCountsEntry"];
export type UserListResponse = components["schemas"]["UserListResponse"];
export type UserCreate = components["schemas"]["UserCreate"];
export type UserUpdate = components["schemas"]["UserUpdate"];
export type UserBlastRadius = components["schemas"]["UserBlastRadius"];
export type ProductListResponse = components["schemas"]["ProductListResponse"];
export type ProductResponse = components["schemas"]["ProductResponse"];
export type DocumentResponse = components["schemas"]["DocumentResponse"];
export type AccountListResponse = components["schemas"]["AccountListResponse"];
export type AccountListPage = components["schemas"]["PaginatedResponse_AccountListResponse_"];
export type AccountResponse = components["schemas"]["AccountResponse"];
export type AccountCountsEntry = components["schemas"]["AccountCountsEntry"];
export type NotificationResponse = components["schemas"]["NotificationResponse"];
export type UnreadCountResponse = components["schemas"]["UnreadCountResponse"];
export type AuditLogResponse = components["schemas"]["AuditLogResponse"];
export type AuditLogPage = components["schemas"]["PaginatedResponse_AuditLogResponse_"];
export type MarketingLeadResponse = components["schemas"]["MarketingLeadResponse"];
export type MarketingLeadCreate = components["schemas"]["MarketingLeadCreate"];
export type MarketingLeadDiscard = components["schemas"]["MarketingLeadDiscard"];
