/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/master-data/{entity_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Master Data */
        get: operations["list_master_data_api_v1_master_data__entity_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Counts */
        get: operations["get_account_counts_api_v1_accounts_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_v1_accounts__account_id__get"];
        /** Update Account */
        put: operations["update_account_api_v1_accounts__account_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_accounts__account_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/stakeholders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stakeholders */
        get: operations["list_stakeholders_api_v1_accounts__account_id__stakeholders_get"];
        put?: never;
        /** Create Stakeholder */
        post: operations["create_stakeholder_api_v1_accounts__account_id__stakeholders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stakeholders/{stakeholder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Stakeholder */
        put: operations["update_stakeholder_api_v1_stakeholders__stakeholder_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/installed-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Installed Assets */
        get: operations["list_installed_assets_api_v1_accounts__account_id__installed_assets_get"];
        put?: never;
        /** Create Installed Asset */
        post: operations["create_installed_asset_api_v1_accounts__account_id__installed_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/installed-assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Installed Asset */
        put: operations["update_installed_asset_api_v1_installed_assets__asset_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Projects */
        get: operations["list_all_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_accounts__account_id__projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_accounts__account_id__projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Project */
        put: operations["update_project_api_v1_projects__project_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_v1_accounts__account_id__opportunities_get"];
        put?: never;
        /** Create Opportunity */
        post: operations["create_opportunity_api_v1_accounts__account_id__opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Opportunity */
        put: operations["update_opportunity_api_v1_opportunities__opportunity_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunity Items */
        get: operations["list_opportunity_items_api_v1_opportunities__opportunity_id__items_get"];
        put?: never;
        /** Add Opportunity Item */
        post: operations["add_opportunity_item_api_v1_opportunities__opportunity_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunity-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Opportunity Item */
        delete: operations["delete_opportunity_item_api_v1_opportunity_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count Products */
        get: operations["count_products_api_v1_products_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__product_id__get"];
        /** Update Product */
        put: operations["update_product_api_v1_products__product_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIResponse[AccountDetailResponse] */
        APIResponse_AccountDetailResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["AccountDetailResponse"];
        };
        /** APIResponse[AccountResponse] */
        APIResponse_AccountResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["AccountResponse"];
        };
        /** APIResponse[InstalledAssetResponse] */
        APIResponse_InstalledAssetResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["InstalledAssetResponse"];
        };
        /** APIResponse[OpportunityItemResponse] */
        APIResponse_OpportunityItemResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["OpportunityItemResponse"];
        };
        /** APIResponse[OpportunityResponse] */
        APIResponse_OpportunityResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["OpportunityResponse"];
        };
        /** APIResponse[PaginatedResponse[AccountListResponse]] */
        APIResponse_PaginatedResponse_AccountListResponse__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["PaginatedResponse_AccountListResponse_"];
        };
        /** APIResponse[PaginatedResponse[ProductListResponse]] */
        APIResponse_PaginatedResponse_ProductListResponse__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["PaginatedResponse_ProductListResponse_"];
        };
        /** APIResponse[PaginatedResponse[UserListResponse]] */
        APIResponse_PaginatedResponse_UserListResponse__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["PaginatedResponse_UserListResponse_"];
        };
        /** APIResponse[PaginatedResponse[WorkspaceProjectWithAccount]] */
        APIResponse_PaginatedResponse_WorkspaceProjectWithAccount__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["PaginatedResponse_WorkspaceProjectWithAccount_"];
        };
        /** APIResponse[ProductResponse] */
        APIResponse_ProductResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["ProductResponse"];
        };
        /** APIResponse[ProjectResponse] */
        APIResponse_ProjectResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["ProjectResponse"];
        };
        /** APIResponse[StakeholderResponse] */
        APIResponse_StakeholderResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["StakeholderResponse"];
        };
        /** APIResponse[UserMeResponse] */
        APIResponse_UserMeResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["UserMeResponse"];
        };
        /** APIResponse[WorkspaceResponse] */
        APIResponse_WorkspaceResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data: components["schemas"]["WorkspaceResponse"];
        };
        /** APIResponse[dict[str, AccountCountsEntry]] */
        APIResponse_dict_str__AccountCountsEntry__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: {
                [key: string]: components["schemas"]["AccountCountsEntry"];
            };
        };
        /** APIResponse[int] */
        APIResponse_int_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: number;
        };
        /** APIResponse[list] */
        APIResponse_list_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: unknown[];
        };
        /** APIResponse[list[OpportunityItemResponse]] */
        APIResponse_list_OpportunityItemResponse__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: components["schemas"]["OpportunityItemResponse"][];
        };
        /** APIResponse[list[StakeholderResponse]] */
        APIResponse_list_StakeholderResponse__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: components["schemas"]["StakeholderResponse"][];
        };
        /** APIResponse[list[WorkspaceInstalledAsset]] */
        APIResponse_list_WorkspaceInstalledAsset__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: components["schemas"]["WorkspaceInstalledAsset"][];
        };
        /** APIResponse[list[WorkspaceOpportunity]] */
        APIResponse_list_WorkspaceOpportunity__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: components["schemas"]["WorkspaceOpportunity"][];
        };
        /** APIResponse[list[WorkspaceProject]] */
        APIResponse_list_WorkspaceProject__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: components["schemas"]["WorkspaceProject"][];
        };
        /** AccountCountsEntry */
        AccountCountsEntry: {
            /** Stakeholder Count */
            stakeholder_count: number;
            /** Project Count */
            project_count: number;
            /** Opportunity Count */
            opportunity_count: number;
            /** Asset Count */
            asset_count: number;
        };
        /** AccountCreate */
        AccountCreate: {
            /** Name */
            name: string;
            /** Parent Account Id */
            parent_account_id?: string | null;
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
            payer_behavior?: components["schemas"]["PayerBehavior"] | null;
        };
        /** AccountDetailResponse */
        AccountDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Account Id */
            parent_account_id: string | null;
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
            /** Payer Behavior */
            payer_behavior: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            zone: components["schemas"]["ZoneNested"];
            parent_account: components["schemas"]["AccountListResponse"] | null;
            /** Stakeholder Count */
            stakeholder_count: number;
            /** Project Count */
            project_count: number;
            /** Opportunity Count */
            opportunity_count: number;
            /** Asset Count */
            asset_count: number;
        };
        /** AccountListResponse */
        AccountListResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Account Id */
            parent_account_id: string | null;
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
            /** Payer Behavior */
            payer_behavior: string | null;
            zone: components["schemas"]["ZoneNested"];
        };
        /** AccountNested */
        AccountNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** AccountResponse */
        AccountResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Account Id */
            parent_account_id: string | null;
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
            /** Payer Behavior */
            payer_behavior: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            zone: components["schemas"]["ZoneNested"];
            parent_account: components["schemas"]["AccountListResponse"] | null;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Account Id */
            parent_account_id?: string | null;
            /** Zone Id */
            zone_id?: string | null;
            payer_behavior?: components["schemas"]["PayerBehavior"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** InstalledAssetCreate */
        InstalledAssetCreate: {
            /** Product Id */
            product_id?: string | null;
            /**
             * Is Competitor Equipment
             * @default false
             */
            is_competitor_equipment: boolean;
            /** Competitor Product Name */
            competitor_product_name?: string | null;
            /** Installation Date */
            installation_date?: string | null;
            /** Department */
            department?: string | null;
        };
        /** InstalledAssetResponse */
        InstalledAssetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Product Id */
            product_id: string | null;
            /** Is Competitor Equipment */
            is_competitor_equipment: boolean;
            /** Competitor Product Name */
            competitor_product_name: string | null;
            /** Installation Date */
            installation_date: string | null;
            /** Department */
            department: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InstalledAssetUpdate */
        InstalledAssetUpdate: {
            /** Product Id */
            product_id?: string | null;
            /** Is Competitor Equipment */
            is_competitor_equipment?: boolean | null;
            /** Competitor Product Name */
            competitor_product_name?: string | null;
            /** Installation Date */
            installation_date?: string | null;
            /** Department */
            department?: string | null;
        };
        /**
         * MasterDataEntity
         * @enum {string}
         */
        MasterDataEntity: "stages" | "statuses" | "project-statuses" | "lead-sources" | "loss-reasons" | "hold-reasons" | "sbus" | "zones";
        /** OpportunityCreate */
        OpportunityCreate: {
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /**
             * Status Id
             * Format: uuid
             */
            status_id: string;
            /** Win Probability */
            win_probability: number | string;
            /** Project Id */
            project_id?: string | null;
            /** Lead Source Id */
            lead_source_id?: string | null;
            /** Indicative Value */
            indicative_value?: number | string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OpportunityItemCreate"][];
        };
        /** OpportunityItemCreate */
        OpportunityItemCreate: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
            /** Unit Price Lakhs */
            unit_price_lakhs: number | string;
            /**
             * Discount Lakhs
             * @default 0
             */
            discount_lakhs: number | string;
        };
        /** OpportunityItemResponse */
        OpportunityItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
            /** Unit Price Lakhs */
            unit_price_lakhs: string;
            /** Discount Lakhs */
            discount_lakhs: string;
            /** Extended Value Lakhs */
            extended_value_lakhs: string;
            product: components["schemas"]["app__domains__opportunity__schemas__ProductNested"];
        };
        /** OpportunityResponse */
        OpportunityResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Sbu Id
             * Format: uuid
             */
            sbu_id: string;
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /**
             * Status Id
             * Format: uuid
             */
            status_id: string;
            /** Win Probability */
            win_probability: string;
            /** Project Id */
            project_id: string | null;
            /** Lead Source Id */
            lead_source_id: string | null;
            /** Indicative Value */
            indicative_value: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            sbu: components["schemas"]["SBUNested"];
        };
        /** OpportunityStageNested */
        OpportunityStageNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stage Code */
            stage_code: string;
            /** Stage Name */
            stage_name: string;
        };
        /** OpportunityStatusNested */
        OpportunityStatusNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status Code */
            status_code: string;
            /** Status Name */
            status_name: string;
        };
        /** OpportunityUpdate */
        OpportunityUpdate: {
            /** Name */
            name?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /** Stage Id */
            stage_id?: string | null;
            /** Status Id */
            status_id?: string | null;
            /** Win Probability */
            win_probability?: number | string | null;
            /** Project Id */
            project_id?: string | null;
            /** Lead Source Id */
            lead_source_id?: string | null;
            /** Indicative Value */
            indicative_value?: number | string | null;
        };
        /** OwnerNested */
        OwnerNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
        };
        /** PaginatedResponse[AccountListResponse] */
        PaginatedResponse_AccountListResponse_: {
            /** Items */
            items: components["schemas"]["AccountListResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[ProductListResponse] */
        PaginatedResponse_ProductListResponse_: {
            /** Items */
            items: components["schemas"]["ProductListResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[UserListResponse] */
        PaginatedResponse_UserListResponse_: {
            /** Items */
            items: components["schemas"]["UserListResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PaginatedResponse[WorkspaceProjectWithAccount] */
        PaginatedResponse_WorkspaceProjectWithAccount_: {
            /** Items */
            items: components["schemas"]["WorkspaceProjectWithAccount"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PayerBehavior
         * @enum {string}
         */
        PayerBehavior: "GOOD" | "AVERAGE" | "PROBLEMATIC" | "UNKNOWN";
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /**
             * Sbu Id
             * Format: uuid
             */
            sbu_id: string;
            /** Oem Name */
            oem_name?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Category Name */
            category_name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ProductListResponse */
        ProductListResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Sbu Id
             * Format: uuid
             */
            sbu_id: string;
            /** Oem Name */
            oem_name: string | null;
            /** Model Number */
            model_number: string | null;
            /** Category Name */
            category_name: string | null;
            /** Is Active */
            is_active: boolean | null;
            sbu: components["schemas"]["SBUNested"];
        };
        /** ProductResponse */
        ProductResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Sbu Id
             * Format: uuid
             */
            sbu_id: string;
            /** Oem Name */
            oem_name: string | null;
            /** Model Number */
            model_number: string | null;
            /** Category Name */
            category_name: string | null;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            sbu: components["schemas"]["SBUNested"];
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Sbu Id */
            sbu_id?: string | null;
            /** Oem Name */
            oem_name?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Category Name */
            category_name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Status Id
             * Format: uuid
             */
            status_id: string;
            /** Bid Submission Date */
            bid_submission_date?: string | null;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Status Id
             * Format: uuid
             */
            status_id: string;
            /** Bid Submission Date */
            bid_submission_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectStatusNested */
        ProjectStatusNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status Code */
            status_code: string;
            /** Status Name */
            status_name: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /** Status Id */
            status_id?: string | null;
            /** Bid Submission Date */
            bid_submission_date?: string | null;
        };
        /** SBUNested */
        SBUNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** StakeholderCreate */
        StakeholderCreate: {
            /** Name */
            name: string;
            /** Designation */
            designation?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Nps Score */
            nps_score?: number | null;
            /** Sentiment */
            sentiment?: string | null;
        };
        /** StakeholderResponse */
        StakeholderResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Name */
            name: string;
            /** Designation */
            designation: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Nps Score */
            nps_score: number | null;
            /** Sentiment */
            sentiment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StakeholderUpdate */
        StakeholderUpdate: {
            /** Name */
            name?: string | null;
            /** Designation */
            designation?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Nps Score */
            nps_score?: number | null;
            /** Sentiment */
            sentiment?: string | null;
        };
        /** UserListResponse */
        UserListResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /**
             * Sbu Id
             * Format: uuid
             */
            sbu_id: string;
            /** Zone Id */
            zone_id: string | null;
            /**
             * Role Id
             * Format: uuid
             */
            role_id: string;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean | null;
            /** Role Name */
            role_name: string;
            sbu: components["schemas"]["SBUNested"];
            zone: components["schemas"]["ZoneNested"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** WorkspaceAccount */
        WorkspaceAccount: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Account Id */
            parent_account_id: string | null;
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
            /** Payer Behavior */
            payer_behavior: string | null;
            zone: components["schemas"]["ZoneNested"];
        };
        /** WorkspaceInstalledAsset */
        WorkspaceInstalledAsset: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            product: components["schemas"]["app__domains__account__workspace_schemas__ProductNested"] | null;
            /** Is Competitor Equipment */
            is_competitor_equipment: boolean;
            /** Competitor Product Name */
            competitor_product_name: string | null;
            /** Installation Date */
            installation_date: string | null;
            /** Department */
            department: string | null;
        };
        /** WorkspaceOpportunity */
        WorkspaceOpportunity: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string | null;
            /** Lead Source Id */
            lead_source_id: string | null;
            /**
             * Sbu Id
             * Format: uuid
             */
            sbu_id: string;
            /** Win Probability */
            win_probability: string;
            /** Indicative Value */
            indicative_value: string | null;
            stage: components["schemas"]["OpportunityStageNested"];
            status: components["schemas"]["OpportunityStatusNested"];
            owner: components["schemas"]["OwnerNested"];
            sbu: components["schemas"]["SBUNested"];
        };
        /** WorkspaceProject */
        WorkspaceProject: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatusNested"];
            owner: components["schemas"]["OwnerNested"];
            /** Bid Submission Date */
            bid_submission_date: string | null;
        };
        /** WorkspaceProjectWithAccount */
        WorkspaceProjectWithAccount: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatusNested"];
            owner: components["schemas"]["OwnerNested"];
            /** Bid Submission Date */
            bid_submission_date: string | null;
            account: components["schemas"]["AccountNested"];
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            account: components["schemas"]["WorkspaceAccount"];
            /** Stakeholders */
            stakeholders: components["schemas"]["WorkspaceStakeholder"][];
            /** Projects */
            projects: components["schemas"]["WorkspaceProject"][];
            /** Opportunities */
            opportunities: components["schemas"]["WorkspaceOpportunity"][];
            /** Installed Assets */
            installed_assets: components["schemas"]["WorkspaceInstalledAsset"][];
        };
        /** WorkspaceStakeholder */
        WorkspaceStakeholder: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Designation */
            designation: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Nps Score */
            nps_score: number | null;
            /** Sentiment */
            sentiment: string | null;
        };
        /** ZoneNested */
        ZoneNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ProductNested */
        app__domains__account__workspace_schemas__ProductNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Oem Name */
            oem_name: string | null;
            /** Model Number */
            model_number: string | null;
        };
        /** ProductNested */
        app__domains__opportunity__schemas__ProductNested: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_UserMeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_master_data_api_v1_master_data__entity_name__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_name: components["schemas"]["MasterDataEntity"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_PaginatedResponse_UserListResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_api_v1_accounts_get: {
        parameters: {
            query?: {
                search?: string | null;
                zone_id?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_PaginatedResponse_AccountListResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_AccountResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_counts_api_v1_accounts_counts_get: {
        parameters: {
            query: {
                /** @description Comma-separated account UUIDs */
                ids: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_dict_str__AccountCountsEntry__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_api_v1_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_AccountDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_v1_accounts__account_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_AccountResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_accounts__account_id__workspace_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_WorkspaceResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stakeholders_api_v1_accounts__account_id__stakeholders_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_StakeholderResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stakeholder_api_v1_accounts__account_id__stakeholders_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StakeholderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_StakeholderResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stakeholder_api_v1_stakeholders__stakeholder_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                stakeholder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StakeholderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_StakeholderResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_installed_assets_api_v1_accounts__account_id__installed_assets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_WorkspaceInstalledAsset__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_installed_asset_api_v1_accounts__account_id__installed_assets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstalledAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_InstalledAssetResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_installed_asset_api_v1_installed_assets__asset_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstalledAssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_InstalledAssetResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                search?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_PaginatedResponse_WorkspaceProjectWithAccount__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_accounts__account_id__projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_WorkspaceProject__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_accounts__account_id__projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ProjectResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ProjectResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_v1_accounts__account_id__opportunities_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_WorkspaceOpportunity__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_api_v1_accounts__account_id__opportunities_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_OpportunityResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_opportunity_api_v1_opportunities__opportunity_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_OpportunityResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunity_items_api_v1_opportunities__opportunity_id__items_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_OpportunityItemResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_opportunity_item_api_v1_opportunities__opportunity_id__items_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_OpportunityItemResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_opportunity_item_api_v1_opportunity_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                search?: string | null;
                sbu_id?: string | null;
                page?: number;
                page_size?: number;
                include_count?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_PaginatedResponse_ProductListResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_products_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ProductResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_products_api_v1_products_count_get: {
        parameters: {
            query?: {
                search?: string | null;
                sbu_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_int_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ProductResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ProductResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
